# Generated by Django 4.0.6 on 2022-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='shortdesc',
            field=models.TextField(null=True),
        ),
    ]
